# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyhelper2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
