# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-01 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handyhelper2_app', '0002_auto_20190801_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='desc',
            new_name='descriptionription',
        ),
    ]
